version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: next_frontend
    networks:
      - app-network
    volumes:
      - ./frontend:/var/www/html
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: laravel_backend
    networks:
      - app-network
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: app_db
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
